from __future__ import annotations


SUPPORTED_ACTIONS = {
    "system_info",
    "storage_info",
    "create_upload",
    "create_download",
    "delete_storage_objects",
    "volume_upload_init",
    "volume_upload_chunk",
    "volume_upload_finalize",
    "volume_file_info",
    "volume_file_chunk",
    "volume_delete",
    "align_lyrics",
    "align_lyrics_smart",
    "aligner_info",
    "analyze_audio",
    "analyze_audio_v2",
    "compare_audio",
    "compare_audio_v2",
    "inspect_stems",
    "inspect_stems_v2",
    "separate_stems",
    "stem_remix",
    "mastering_plan",
    "legacy_mastering_plan",
    "master_audio",
    "master_audio_github_delivery",
    "full_pass",
    "repair_audio",
    "humanize_audio",
    "naturalize",
    "render_lyric_video",
    "export_daw",
    "get_memory",
    "record_feedback",
    "record_rule",
    "get_production_profile",
}
